# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
id: ihe.iti.mhds
canonical: http://profiles.ihe.net/ITI/MHDS
version: 2.1.1
name: IHE_ITI_MHDS
title: "Mobile Health Document Sharing"
status: active
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
description: This Implementation Guide shows how to build a Document Sharing Exchange using IHE-profiled FHIR standard, rather than the legacy IHE profiles that are dominated by XDS and HL7 v2. This Implementation Guide assembles other IHE Implementation guides (Profiles) and defines a Document Registry Actor.
license:  CC-BY-SA-4.0
fhirVersion: 4.0.1
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2021+
releaseLabel: ci-build
dependencies:
  ihe.mhd.fhir: 
    id: ihemhdfhir
    uri: http://profiles.ihe.net/ITI/MHD/ImplementationGuide/ihe.mhd.fhir
    version: 4.0.2
  IHE.ITI.PDQm: 
    id: ihepdqm
    uri: http://profiles.ihe.net/ITI/PDQm/ImplementationGuide/IHE.ITI.PDQm
    version: 2.3.0


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: "MHDS Home"
    generation: markdown
  volume-1.md:
    title: "1:50. MHDS Volume 1"
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: "Open and Closed issues"
    generation: markdown

menu:
  MHDS Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#1501-mhds-actors-transactions-and-content-modules
    Actor Options: volume-1.html#1502-mhds-actor-options
    Required Groupings: volume-1.html#1503-mhds-required-actor-groupings
    Overview: volume-1.html#1504-mhds-overview
    Security Considerations: volume-1.html#1505-mhds-security-considerations
    Cross-Profile Considerations: volume-1.html#1506-mhds-cross-profile-considerations
  Test Plan: testplan.html
  Artifacts: artifacts.html
